name: GitHub CI

on: [push, pull_request]

jobs:
  Drift:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14.x, 16.x, 18.x]
        os: [ubuntu-latest]
        # os: [macOS-latest]
        # os: [ubuntu-latest, macOS-latest]
        # os: [ubuntu-latest, windows-latest]
    steps:
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: latest
      - run: chrome --version
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Packages
        run: npm install
      - name: Build and Test
        run: npm run test